Repository local-mark/backend, pull requests merged in 2024-08, with the labels that each got.

#25 [FIX] post.dao, post.service 에러 해결(#24)
  src/models/post.dao.js
  src/services/post.service.js
Labels: 🐞 BugFix

#27 [FEAT] 로그인, 로그아웃 구현 (#15)
  config/baseResponseStatus.js
  config/error.js
  config/response.status.js
  config/userJwtMiddleWare.js
  index.js
  package-lock.json
  package.json
  src/controllers/auth.controller.js
  src/controllers/user.controller.js
  src/models/auth.dao.js
  src/models/auth.sql.js
  src/models/user.sql.js
  src/routes/auth.route.js
  src/routes/user.route.js
  src/services/auth.service.js
  swagger/auth.swagger.yml
Labels: ✨ Feature

#12 [Feat] 댓글과 대댓글 작성, 삭제, 조회 기능 (#4)
  index.js
  src/controllers/comment.controller.js
  src/controllers/post.controller.js
  src/models/comment.dao.js
  src/models/comment.sql.js
  src/models/post.dao.js
  src/models/post.sql.js
  src/providers/comment.provider.js
  src/routes/comment.route.js
  src/routes/post.route.js
  src/services/comment.service.js
  src/services/post.service.js
Labels: ✨ Feature

#36 [CI] CI/CD deploy.yml 수정
  .github/workflows/dev_deploy.yml
Labels: 👷 ci

#14 [FEAT] More Local 게시글 조회 기능(#8)
  config/db.config.js
  config/response.status.js
  index.js
  src/controllers/morelocal.controller.js
  src/dtos/morelocal.dto.js
  src/models/morelocal.dao.js
  src/models/morelocal.sql.js
  src/proviers/morelocal.provider.js
  src/routes/morelocal.routes.js
  swagger/morelocal.swagger.yaml
Labels: ✨ Feature

#23 [FEAT] 브랜드 등록 / 정보 변경 (#3)
  index.js
  package-lock.json
  package.json
  src/controllers/brand.controller.js
  src/dtos/brand.dto.js
  src/models/brand.dao.js
  src/models/post.dao.js
  src/providers/brand.provider.js
  src/providers/user.providers.js
  src/routes/brand.route.js
  src/services/brand.service.js
  src/services/post.service.js
  swagger/brand.swagger.yaml
  swagger/user.swagger.yaml
  yarn.lock
Labels: ✨ Feature

#50 [FEAT] 브랜드 정보/제품 갤러리 조회 API 구현(#16)
  config/response.status.js
  index.js
  src/controllers/brand.controller.js
  src/dtos/brand.dto.js
  src/models/brand.dao.js
  src/models/brand.sql.js
  src/proviers/brand.providers.js
  src/routes/brand.route.js
  swagger/brand.swagger.yaml
Labels: ✨ Feature

#52 [FEAT] Authorization 관련 세팅 #51
  config/swagger.config.js
  config/userJwtMiddleWare.js
Labels: ⚙ Setting

#54 [Refactor] DB에 맞게 query 변경(#15)
  src/models/auth.sql.js
Labels: 🔨 Refactor

#57 [FIX] index.js 에러 발생 해결 (#56)
  index.js
  src/routes/user.route.js
Labels: 🐞 BugFix

#55 [FEAT] 제품 갤러리 API 구현 (#5)
  index.js
  package-lock.json
  src/controllers/gallery.controller.js
  src/dtos/gallery.dto.js
  src/models/gallery.dao.js
  src/models/gallery.sql.js
  src/proviers/gallery.provider.js
  src/routes/gallery.routes.js
  swagger/gallery.swagger.yaml
Labels: ✨ Feature

#53 [FEAT] 리뷰 조회/작성/수정/삭제 기능 구현 (#44)
  config/response.status.js
  config/swagger.config.js
  index.js
  package-lock.json
  package.json
  src/controllers/review.controller.js
  src/dtos/review.dto.js
  src/middleware/image.uploader.js
  src/middleware/uuid.js
  src/models/review.dao.js
  src/models/review.sql.js
  src/providers/review.provider.js
  src/routes/health.route.js
  src/routes/review.route.js
  src/services/review.service.js
  swagger/review.swagger.yml
  yarn.lock
Labels: ✨ Feature

#59 [FEAT] 마이페이지 구현 (#20)
  index.js
  package-lock.json
  package.json
  src/controllers/user.controller.js
  src/models/post.dao.js
  src/models/user.dao.js
  src/routes/post.route.js
  src/routes/user.route.js
  src/services/user.service.js
  swagger/user.swagger.yaml
  yarn.lock
Labels: ✨ Feature

#26 [FEAT] 게시글 상세페이지 조회 및 수정,삭제 & 이미지 업로드 및 삭제 (#6)
  index.js
  package-lock.json
  package.json
  src/controllers/post.controller.js
  src/dtos/image.dto.js
  src/dtos/post.dto.js
  src/models/image.dao.js
  src/models/image.sql.js
  src/models/post.dao.js
  src/models/post.sql.js
  src/providers/post.provider.js
  src/proviers/image.provider.js
  src/routes/post.route.js
  src/services/image.service.js
  src/services/post.service.js
Labels: 🔨 Refactor, ✨ Feature

#64 [FIX] 서버 연결 안됨 해결 (#63)
  index.js
  package-lock.json
  package.json
  src/routes/health.route.js
  yarn.lock
Labels: 🐞 BugFix

#65 [FIX] 서버 연결 안됨 해결 (#63)
  index.js
  src/routes/post.route.js
Labels: 🐞 BugFix

#68 [REFACTOR] proviers에 있는 파일 providers로 옮기기 (#66)
  index.js
  src/controllers/brand.controller.js
  src/controllers/gallery.controller.js
  src/controllers/morelocal.controller.js
  src/providers/brand.provider.js
  src/providers/gallery.provider.js
  src/providers/image.provider.js
  src/providers/morelocal.provider.js
  src/proviers/brand.providers.js
  src/routes/gallery.route.js
  src/routes/morelocal.route.js
Labels: 🔨 Refactor

#60 [FEAT] 비밀번호 찾기, 회원 탈퇴 기능(#28)
  config/email.js
  config/response.status.js
  config/userJwtMiddleWare.js
  jobs/deleteInactiveUsers.js
  src/controllers/auth.controller.js
  src/controllers/user.controller.js
  src/models/auth.dao.js
  src/models/auth.sql.js
  src/models/user.dao.js
  src/models/user.sql.js
  src/routes/user.route.js
  src/services/auth.service.js
  src/services/user.service.js
  swagger/auth.swagger.yml
  swagger/user.swagger.yaml
Labels: ✨ Feature

#70 [REFACTOR] 제품 갤러리 API (#58)
  config/response.status.js
  src/dtos/gallery.dto.js
  src/models/gallery.dao.js
  src/models/gallery.sql.js
  src/providers/gallery.provider.js
  swagger/gallery.swagger.yaml
Labels: 🔨 Refactor

#74 [Refactor] swagger 수정(#28)
  swagger/auth.swagger.yml
  swagger/review.swagger.yml
  swagger/user.swagger.yaml
Labels: ✨ Feature

#75 [Refactor] 브랜드 정보/제품 갤러리 수정(#16)
  src/models/brand.sql.js
  swagger/brand.swagger.yaml
Labels: 🔨 Refactor, ✨ Feature

#76 [Refactor] More Local 게시글 조회 Swagger 수정(#8)
  swagger/morelocal.swagger.yaml
Labels: 🔨 Refactor

#78 [Refactor] 브랜드 정보/제품 갤러리 스웨거 추가 수정(#16)
  swagger/brand.swagger.yaml
Labels: 🔨 Refactor

#77 [REFACTOR] 제품 갤러리 수정(#58)
  src/models/gallery.dao.js
  src/models/gallery.sql.js
  swagger/gallery.swagger.yaml
Labels: 🔨 Refactor, ✨ Feature

#71 [REFACTOR] 크리에이터 커뮤니티 조회 시 댓글 수, 좋아요 수 포함( #32)
  src/controllers/comment.controller.js
  src/controllers/post.controller.js
  src/dtos/comment.dto.js
  src/dtos/post.dto.js
  src/models/Like.dao.js
  src/models/Like.sql.js
  src/models/comment.dao.js
  src/models/comment.sql.js
  src/models/image.dao.js
  src/models/post.sql.js
  src/providers/comment.provider.js
  src/providers/post.provider.js
  src/routes/post.route.js
  src/services/image.service.js
  src/services/post.service.js
  swagger/comment.swagger.yaml
  swagger/likes.swagger.yaml
Labels: 🔨 Refactor, ✨ Feature

#80 [FIX] swagger 수정 및 회원가입 시 이메일 인증 기능 추가
  config/swagger.config.js
  package.json
  src/controllers/user.controller.js
  src/models/user.dao.js
  src/routes/user.route.js
  src/services/user.service.js
  swagger/user.swagger.yaml
Labels: 🐞 BugFix

#72 [FEAT] socket.io 채팅 전송/ 채팅방 조회/ 내역 조회 구현 (#31)
  config/response.status.js
  index.js
  package-lock.json
  package.json
  src/controllers/chat.controller.js
  src/middleware/socket.js
  src/models/chat.dao.js
  src/models/chat.sql.js
  src/providers/chat.provider.js
  src/routes/chat.route.js
  src/services/chat.service.js
  swagger/chat.swagger.yaml
  swagger/likes.swagger.yaml
  yarn.lock
Labels: ✨ Feature

#69 [REFACTOR] 이미지 s3 업로드 및 코드 수정
  index.js
  src/controllers/post.controller.js
  src/dtos/post.dto.js
  src/models/brand.sql.js
  src/models/image.dao.js
  src/models/image.sql.js
  src/models/post.dao.js
  src/models/post.sql.js
  src/routes/brand.route.js
  src/routes/post.route.js
  src/services/post.service.js
  swagger/post.swagger.yml
Labels: 🔨 Refactor, 📃 Docs

#83 [FIX] swagger 수정
  config/database.js
  config/swagger.config.js
  src/models/brand.dao.js
  src/providers/image.provider.js
  swagger/brand.swagger.yaml
Labels: 🐞 BugFix

#90 [Refactor] index.js 수정(#8)
  index.js
Labels: 🔨 Refactor

#95 [Fix] User 아이디 찾기 시 nickname undefined 수정(#20)
  src/models/user.dao.js
  src/services/user.service.js
  swagger/user.swagger.yaml
Labels: 🐞 BugFix

#96 [REFACTOR] More Local 게시글 조회 사진 추가 (#93)
  src/dtos/morelocal.dto.js
  src/models/morelocal.dao.js
  src/models/morelocal.sql.js
  src/providers/morelocal.provider.js
  swagger/morelocal.swagger.yaml
Labels: 🔨 Refactor, ✨ Feature

#94 [Fix, Refactor] post 부분 코드 수정 및 swagger 문서 수정, 머지 충돌 오류 해결
  config/swagger.config.js
  src/controllers/post.controller.js
  src/dtos/post.dto.js
  src/models/image.dao.js
  src/models/image.sql.js
  src/models/post.dao.js
  src/models/post.sql.js
  src/providers/post.provider.js
  src/services/post.service.js
  swagger/post.swagger.yml
Labels: 🐞 BugFix, 🔨 Refactor

#99 [Refactor] 댓글 작성에 로그인 한 유저 ID 사용하도록 변경
  src/controllers/comment.controller.js
  src/routes/comment.route.js
  src/services/comment.service.js
  swagger/comment.swagger.yaml
Labels: 🔨 Refactor

#100 [Refactor] swagger.config.js 파일 수정(#62)
  config/swagger.config.js
Labels: 🔨 Refactor

#102 [Fix] 닉네임 포함하여 크리에이터 회원가입하도록 재수정
  src/models/user.dao.js
  src/services/user.service.js
  swagger/user.swagger.yaml
Labels: 🐞 BugFix

#103 [Refactor] 게시글 수정, 조회 코드 수정
  src/controllers/post.controller.js
  src/dtos/post.dto.js
  src/models/image.sql.js
  src/models/post.dao.js
  src/models/post.sql.js
  src/providers/post.provider.js
  src/services/post.service.js
  swagger/post.swagger.yml
Labels: 🔨 Refactor

#104 [Fix] type 구분없이 회원가입
  src/controllers/user.controller.js
  src/models/user.dao.js
  src/routes/user.route.js
  src/services/user.service.js
  swagger/user.swagger.yaml
Labels: 🐞 BugFix

#105 [FEAT] is_brand_registered 추가, User info 가져오는 api 추가
  src/controllers/auth.controller.js
  src/controllers/brand.controller.js
  src/controllers/user.controller.js
  src/models/auth.sql.js
  src/models/user.dao.js
  src/routes/brand.route.js
  src/routes/user.route.js
  src/services/auth.service.js
  src/services/brand.service.js
  src/services/user.service.js
  swagger/user.swagger.yaml
Labels: ✨ Feature

#108 [REFACTOR] 제품 옵션 가져오는 값 수정(#58)
  src/models/gallery.dao.js
Labels: 🔨 Refactor

#109 [Refactor] 브랜드 등록 여부 반환 응답 body -> 토큰 payload(#28)
  config/swagger.config.js
  src/controllers/auth.controller.js
Labels: 🔨 Refactor

#107 [FEAT] 주문 수집 조회 API 구현(#49)
  config/response.status.js
  config/userJwtMiddleWare.js
  src/controllers/brand.controller.js
  src/dtos/brand.dto.js
  src/models/brand.dao.js
  src/models/brand.sql.js
  src/providers/brand.provider.js
  src/routes/brand.route.js
  swagger/brand.swagger.yaml
Labels: ✨ Feature

#67 [FEAT] 상품 아이템 장바구니 추가 기능 구현
  config/response.status.js
  index.js
  src/controllers/cart.controller.js
  src/dtos/cart.dto.js
  src/models/cart.dao.js
  src/models/cart.sql.js
  src/models/stock.dao.js
  src/models/stock.sql.js
  src/routes/cart.route.js
  src/services/cart.service.js
  swagger/cart.swagger.yml
Labels: 🔨 Refactor, ✨ Feature

#112 [REFACTOR] 옵션 수정(#49)
  src/models/gallery.dao.js
Labels: 🔨 Refactor

#116 [REFACTOR] 제품 갤러리 상세 조회 상품 설명 조회 방식 수정(#58)
  src/models/gallery.dao.js
  src/models/gallery.sql.js
Labels: 🔨 Refactor

#117 [REFACTOR] 상품 상세 조회 스웨거 수정(#58)
  swagger/gallery.swagger.yaml
Labels: 🔨 Refactor

#13 [FEAT] 상품 등록 기능(#1)
  config/response.js
  config/response.status.js
  index.js
  src/controllers/health.controller.js
  src/controllers/product.controller.js
  src/controllers/user.controller.js
  src/dtos/product.dto.js
  src/middleware/image.uploader.js
  src/models/product.dao.js
  src/models/product.sql.js
  src/models/user.sql.js
  src/routes/product.route.js
  src/services/product.service.js
  swagger/product.swagger.yaml
Labels: ✨ Feature

#118 [FIX] 파일 용량 초과 에러 해결(#1)
  src/middleware/image.uploader.js
Labels: 🐞 BugFix

#119 [Fix] 파일 용량 초과 에러 해결(#1)
  .platform/nginx/nginx.conf
Labels: 🐞 BugFix

#120 [Refactor] 미들웨어 순서 변경(#1)
  src/routes/product.route.js
Labels: 🔨 Refactor

#127 [REFACTOR] 회원가입 시 이메일 인증 구현 수정(#122)
  config/response.status.js
  index.js
  src/controllers/user.controller.js
  src/models/user.dao.js
  src/models/user.sql.js
  src/routes/user.route.js
  src/services/user.service.js
  swagger/user.swagger.yaml
Labels: 🔨 Refactor

#128 [FEAT] 이메일 인증 X 시 에러 추가(#122)
  src/models/user.dao.js
Labels: ✨ Feature

#129 [FEAT] More Local 게시글 생성/수정/삭제 API 구현(#98)
  src/controllers/morelocal.controller.js
  src/dtos/morelocal.dto.js
  src/models/morelocal.dao.js
  src/models/morelocal.sql.js
  src/providers/morelocal.provider.js
  src/routes/morelocal.route.js
  swagger/morelocal.swagger.yaml
Labels: ✨ Feature

#131 [FIX] 이메일 안 가는 오류 수정(#130)
  src/models/user.dao.js
  src/services/user.service.js
Labels: 🐞 BugFix

#137 [FEAT] 아임포트를 통한 결제 기능 구현& 주문 생성, 재고 관리 내부 로직 포함
  config/response.status.js
  index.js
  package-lock.json
  package.json
  src/controllers/order.controller.js
  src/models/order.dao.js
  src/models/order.sql.js
  src/providers/user.providers.js
  src/routes/chat.route.js
  src/routes/order.route.js
  src/services/order.service.js
  swagger/chat.swagger.yaml
  swagger/comment.swagger.yaml
  swagger/likes.swagger.yaml
  swagger/order.swagger.yaml
  yarn.lock
Labels: ✨ Feature

#139 [REFACTOR] 이메일 인증 시 화면 닫히도록 변경(#122)
  src/controllers/user.controller.js
  src/services/user.service.js
Labels: 🔨 Refactor

#140 [REFACTOR] 이메일 인증 시 alert창 텍스트 변경(#122)
  src/controllers/user.controller.js
Labels: 🔨 Refactor
